### ISSUE TITLE
Provide a beneficiary.

### ISSUE THREAD

**Issue by LsrlYrsc** [SilverstoneMC/ExpensiveDeaths#5]
### The suggestion

`amount-to-take: 100.00`
`Beneficiary:Player`
The player will receive 100 for someone else's death
My translation may not be accurate. If u don't understand, I will revise the text.

### Why it would be useful

<del>Such as the doctor-patient relationship.</del>
This is interesting.

**Comment by JasonHorkles** [comment]
This can already be accomplished by using the advanced command execution and giving the killer the amount of money the first player lost.
