### ISSUE TITLE
Permission group based expensive deaths

### ISSUE THREAD

**Issue by shawn695** [SilverstoneMC/ExpensiveDeaths#6]
### The suggestion

have diffrent groups/perms that allow to have differnt death costs

### Why it would be useful

fer server with ranks and vip/mvp you could rank up to loose less money on death

**Comment by shawn695** [comment]
i also would like to add, if killed by another player that, that player would get the balance that the dead player lost

**Comment by JasonHorkles** [comment]
As for your second suggestion, this can already be accomplished by running a command in the console-commands-on-killed section
